Added modal
FoRoKo1o/ChessagonClient pull request #2
Opened 2024-10-17 16:13 UTC by SEGMK

-added html modal element
-added modal logic
-added SiteHexGraber

2024-10-17 16:14 UTC, FoRoKo1o commented
🚢

2024-10-17 16:20 UTC, FoRoKo1o requested changes
Close modal will brake our game.

2024-10-17 16:20 UTC, FoRoKo1o commented on html/board.html
> +                            <div id="hexboard" class="hexboard"> <!--huuuuuuuuge pice of... board-->
I dont like this comment :)

2024-10-17 16:20 UTC, FoRoKo1o commented on html/board.html
> -                            </div>
was is das?

2024-10-17 16:20 UTC, FoRoKo1o commented on css/myModal.css
> +    width: 50%; /* Could be more or less, depending on screen size */
Very good comments from w3

2024-10-17 16:20 UTC, FoRoKo1o commented on css/myModal.css
> +  /* The Close Button */
Do we use that?
Do we need to close modal when we promote pawn?
What if someone close modal without promotion?

2024-10-17 16:20 UTC, FoRoKo1o commented on js/promotionModalController.js
We need to test that

2024-10-18 10:55 UTC, FoRoKo1o approved these changes

2024-10-18 12:52 UTC, merged

2024-10-18 12:53 UTC, SEGMK commented
looks good (but with classes would look even better) 🚢